// Global stylesheet.

import { StyleSheet } from 'react-native';
import { Dimensions } from "react-native";

const windowWidth = Dimensions.get("window").width;

const globalStyles = StyleSheet.create({
    screen: { //used to set the background color of every screen and adjust for the bottomnav.
        backgroundColor: '#CBE6E0',
        flex: 1,
        paddingBottom: 70
    },
    input: { // used for input fields in login and register and so on.
        width: 238,
        height: 43.88,
        flexShrink: 0,
        fontSize: 18,
        borderRadius: 8,
        flexDirection: "row",
        margin: 1,
        borderStyle: "solid",
        alignSelf: "center",
        borderColor: "#00000029",
        borderWidth: 1,
        backgroundColor: "#F1F1F1",
        fontFamily: "Imprima-Regular",
        paddingHorizontal: 10,
        marginTop: 11,
    },
    logo: { // logo shown in login and register
        marginTop: 74,
        alignItems: "center",
        alignSelf: "center",
        width: 241.588,
        height: 87,

    },
    gradient: { //gradient style in login and register
        flex: 0,
        height: '100%',
        width: '100%'
    },
    settingButton: { // buttons on setting screen
        borderWidth: 1,
        borderColor: '#DBDBDB',
        backgroundColor: '#FFF',
        width: '100%',
        height: 50,
        flexShrink: 0,
        flexDirection: 'row',
        alignItems: 'center',
        paddingLeft:10,
    },
    settingButton_text: { // text in buttons on setting screen
        color: '#000',
        fontSize: 20,
        fontStyle: 'normal',
        lineHeight: 16 * 1.5,
        alignItems: 'center',
        marginLeft: 10,
        fontFamily: "Imprima-Regular",
    },
    linkText: { // hypertext, color adjustment.
        color: '#21AC8B',
        borderBottomWidth: 1,
        borderBottomColor: '#21AC8B',
        fontFamily: "Imprima-Regular",
    },
    text:{ //normal text
        fontSize: 20,
        alignItems: "center",
        alignSelf: "center",
        fontFamily: "Imprima-Regular",
    },
    profilebox:{ // Used in Home screen. Boxes for browsing profiles.
        flexDirection: "row",
        backgroundColor: "#FFFFFF",
        paddingLeft: 30,
        alignItems: "center",
        width: "100%",
        alignSelf: "center",
        borderColor: "#9D9D9D",
        borderStyle: "solid",
        borderWidth: 1,
        height: 70
    },
    profilebox_text:{ // Text in the profile boxes in Home screen.
        flexShrink: 0,
        color: "#4D4D4D",
        fontFamily: 'Imprima-Regular',
        fontSize: 19,
        fontStyle: 'normal',
    },
    topnavlogo:{ // Logo used in top nav bar
        marginTop: 10,
        alignItems: "center",
        alignSelf: "center",
        width: 198,
        height: 61.878,
    },
    container_topnav:{ // top nav bar
        justifyContent: 'center',
        alignItems: 'center',
    },
    journal_title:{ //Journal component title
        fontFamily: "Imprima-Regular",
        flex: 1,
        marginLeft: 10,
        fontSize: 22,
        color: '#000',
        fontStyle: 'normal',
        fontWeight: "400",
        paddingTop:10
    },
    journal_date:{ //Journal component date
        color: '#00000080',
        fontFamily: "Imprima-Regular",
        flex: 1,
        fontSize: 15,
        fontWeight: "400",
        marginLeft:10,
    },
    journal_desc:{ //Journal component description
        fontFamily: "Imprima-Regular",
        flex: 1,
        marginHorizontal: 10,
        fontSize: 17,
        color: '#000',
        fontStyle: 'normal',
        fontWeight: "400",

    },
    line:{ //Journal component line under title
        width:'80%',
        height:2,
        backgroundColor: '#21AC8B',
        marginLeft: 10,
        marginVertical: 10,
        top:0
    },
    button: { // Button used in login, register, create.
        flexDirection: "row",
        alignSelf: "center",
        justifyContent: "space-between",
        width: 238,
        height: 43.88,
        flexShrink: 0,
        borderRadius: 13,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 0.30)',
        backgroundColor: '#F79967',
        marginTop: 12,
    },
    button_text:{ // Text in buttons
        color: '#FFF',
        textAlign: 'center',
        fontFamily: "Imprima-Regular",
        fontSize: 24,
        fontStyle: 'normal',
        fontWeight: "400",
        lineHeight: 24 * 1.5,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        width: 238,
        height: 43.88,
        flexShrink: 0,

    },
    info:{ //information on create pages.
        width:238,
        alignSelf: "center",
        paddingVertical:'10%'
    },
    entryTitle:{ // Journal entry component Title
        fontFamily: "Imprima-Regular",
        flex: 1,
        marginLeft: '8%',
        fontSize: 30,
        color: '#000',
        fontStyle: 'normal',
        fontWeight: "400",

    },
    entryDesc:{ // Journal entry component Description
        fontFamily: "Imprima-Regular",
        flex: 1,
        marginHorizontal: '8%',
        marginTop:15,
        marginBottom:30,
        fontSize: 16,
        color: '#000',
        fontStyle: 'normal',
        fontWeight: "400",
    },
    journalEditorTitle:{ //Style for when you go into a Journal to view the entries. Title.
        fontFamily: "Imprima-Regular",
        flex: 1,
        marginLeft: 15,
        fontSize: 32,
        color: '#000',
        fontStyle: 'normal',
        fontWeight: "400",
    },
    journalEditorDate:{ //Style for when you go into a Journal to view the entries. Date.
        color: '#00000080',
        fontFamily: "Imprima-Regular",
        flex: 1,
        fontSize: 16,
        fontWeight: "400",
        marginLeft:10,
        position: 'absolute',
        bottom: 5,
        right: 7,
    },
    journalEditorDesc:{ //Style for when you go into a Journal to view the entries. Description.
        fontFamily: "Imprima-Regular",
        flex: 1,
        marginTop: 50,
        marginBottom: 10,
        fontSize: 18,
        color: '#000',
        fontStyle: 'normal',
        fontWeight: "400",
        marginHorizontal:'10%',
        textAlign: 'center',
    },
    thumbnail:{ //Thumbnail photo
        position: 'absolute',
        top: 0,
        left: 0,
        zIndex: 1,
        alignItems: "center"
    },
    entryTitleBox:{ //Title and Date Box container in open Journal.
        flexDirection: "row",
        alignItems: "center",
        alignSelf: "center",
        width: windowWidth*0.8,
        height: 60,
        backgroundColor: '#FBCCB3',
        position: 'absolute',
        top: 170,
        left: windowWidth*0.1,
        zIndex: 3,
        marginBottom:20,

    },
    thumbnailContainer:{ //Container for thumbnail
        height:200,
        alignItems:'center',
        width:windowWidth*1 ,
        flexDirection:'row',
    },
    entry_top:{ //View on top of entries to make only the top event have border radius.
        backgroundColor: "#FBCCB3",
        borderRadius: 14,
        zIndex:1,
        marginTop:20,
        paddingTop:30,
        height:'100%',
        paddingBottom:100,
    }
});

export default globalStyles;
